const PROGRAM_TITLE_MAPPING = {
  'BSA': [
    'Accountants and Auditors',
    'Bill and Account Collectors',
    'Bookkeeping, Accounting, and Auditing Clerks',
    'Budget Analysts',
    'Business Teachers, Postsecondary',
    'Compliance Managers',
    'Compliance Officers',
    'Cost Estimators',
    'Energy Auditors',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'First-Line Supervisors of Retail Sales Workers',
    'New Accounts Clerks',
    'Tax Examiners and Collectors, and Revenue Agents',
    'Tax Preparers',
    'Treasurers and Controllers',
  ],
  'BSBA_ENTREP': [
    'Advertising Sales Agents',
    'Agents and Business Managers of Artists, Performers, and Athletes',
    'Appraisers of Personal and Business Property',
    'Business Continuity Planners',
    'Business Intelligence Analysts',
    'Business Operations Specialists, All Other',
    'Business Teachers, Postsecondary',
    'Computer Systems Analysts',
    'Construction Managers',
    'Cost Estimators',
    'Document Management Specialists',
    'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
    'Driver/Sales Workers',
    'Emergency Management Directors',
    'Farm and Home Management Educators',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'First-Line Supervisors of Retail Sales Workers',
    'General and Operations Managers',
    'Information Technology Project Managers',
    'Management Analysts',
    'Market Research Analysts and Marketing Specialists',
    'Marketing Managers',
    'Parts Salespersons',
    'Project Management Specialists',
    'Real Estate Sales Agents',
    'Retail Salespersons',
    'Sales and Related Workers, All Other',
    'Sales Managers',
    'Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel',
    'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
    'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
    'Search Marketing Strategists',
    'Securities, Commodities, and Financial Services Sales Agents',
    'Security Management Specialists',
    'Solar Sales Representatives and Assessors',
    'Training and Development Managers',
    'Training and Development Specialists',
    'Wind Energy Operations Managers',
  ],
  'BSBA_MARKETING': [
    'Advertising and Promotions Managers',
    'Advertising Sales Agents',
    'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
    'Driver/Sales Workers',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'First-Line Supervisors of Retail Sales Workers',
    'Market Research Analysts and Marketing Specialists',
    'Marketing Managers',
    'Parts Salespersons',
    'Public Relations Managers',
    'Public Relations Specialists',
    'Real Estate Sales Agents',
    'Retail Salespersons',
    'Sales and Related Workers, All Other',
    'Sales Engineers',
    'Sales Managers',
    'Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel',
    'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
    'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
    'Search Marketing Strategists',
    'Securities, Commodities, and Financial Services Sales Agents',
    'Solar Sales Representatives and Assessors',
  ],
  'BSCS': [
    'Aerospace Engineering and Operations Technologists and Technicians',
    'Bioinformatics Scientists',
    'Bioinformatics Technicians',
    'Cartographers and Photogrammetrists',
    'Clinical Data Managers',
    'Computer and Information Research Scientists',
    'Computer and Information Systems Managers',
    'Computer Hardware Engineers',
    'Computer Network Architects',
    'Computer Network Support Specialists',
    'Computer Numerically Controlled Tool Programmers',
    'Computer Occupations, All Other',
    'Computer Programmers',
    'Computer Science Teachers, Postsecondary',
    'Computer Systems Analysts',
    'Computer Systems Engineers/Architects',
    'Computer User Support Specialists',
    'Computer, Automated Teller, and Office Machine Repairers',
    'Data Scientists',
    'Data Warehousing Specialists',
    'Database Administrators',
    'Database Architects',
    'Geographic Information Systems Technologists and Technicians',
    'Health Information Technologists and Medical Registrars',
    'Information Security Analysts',
    'Information Security Engineers',
    'Intelligence Analysts',
    'Network and Computer Systems Administrators',
    'Operations Research Analysts',
    'Software Developers',
    'Software Quality Assurance Analysts and Testers',
    'Web Administrators',
    'Web and Digital Interface Designers',
    'Web Developers',
  ],
  'BSECE': [
    'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
    'Calibration Technologists and Technicians',
    'Computer Network Architects',
    'Computer Network Support Specialists',
    'Computer Systems Analysts',
    'Computer Systems Engineers/Architects',
    'Database Architects',
    'Electrical and Electronic Engineering Technologists and Technicians',
    'Electrical and Electronic Equipment Assemblers',
    'Electrical and Electronics Drafters',
    'Electrical and Electronics Installers and Repairers, Transportation Equipment',
    'Electrical and Electronics Repairers, Commercial and Industrial Equipment',
    'Electrical and Electronics Repairers, Powerhouse, Substation, and Relay',
    'Electrical Engineers',
    'Electrical Power-Line Installers and Repairers',
    'Electronics Engineers, Except Computer',
    'Excavating and Loading Machine and Dragline Operators, Surface Mining',
    'Helpers--Installation, Maintenance, and Repair Workers',
    'Information Security Analysts',
    'Information Security Engineers',
    'Maintenance and Repair Workers, General',
    'Network and Computer Systems Administrators',
    'Public Safety Telecommunicators',
    'Semiconductor Processing Technicians',
    'Software Developers',
    'Solar Photovoltaic Installers',
    'Telecommunications Engineering Specialists',
    'Telecommunications Equipment Installers and Repairers, Except Line Installers',
    'Telecommunications Line Installers and Repairers',
    'Timing Device Assemblers and Adjusters',
    'Wind Turbine Service Technicians',
  ],
  'BSED': [
    'Adapted Physical Education Specialists',
    'Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors',
    'Anthropology and Archeology Teachers, Postsecondary',
    'Area, Ethnic, and Cultural Studies Teachers, Postsecondary',
    'Art, Drama, and Music Teachers, Postsecondary',
    'Business Teachers, Postsecondary',
    'Career/Technical Education Teachers, Middle School',
    'Career/Technical Education Teachers, Postsecondary',
    'Career/Technical Education Teachers, Secondary School',
    'Communications Teachers, Postsecondary',
    'Computer Science Teachers, Postsecondary',
    'Criminal Justice and Law Enforcement Teachers, Postsecondary',
    'Economics Teachers, Postsecondary',
    'Education Administrators, All Other',
    'Education Administrators, Kindergarten through Secondary',
    'Education Administrators, Postsecondary',
    'Education and Childcare Administrators, Preschool and Daycare',
    'Education Teachers, Postsecondary',
    'Educational Instruction and Library Workers, All Other',
    'Educational, Guidance, and Career Counselors and Advisors',
    'Elementary School Teachers, Except Special Education',
    'English Language and Literature Teachers, Postsecondary',
    'Exercise Trainers and Group Fitness Instructors',
    'Family and Consumer Sciences Teachers, Postsecondary',
    'Foreign Language and Literature Teachers, Postsecondary',
    'Geography Teachers, Postsecondary',
    'Health Education Specialists',
    'History Teachers, Postsecondary',
    'Instructional Coordinators',
    'Kindergarten Teachers, Except Special Education',
    'Mathematical Science Teachers, Postsecondary',
    'Middle School Teachers, Except Special and Career/Technical Education',
    'Philosophy and Religion Teachers, Postsecondary',
    'Political Science Teachers, Postsecondary',
    'Postsecondary Teachers, All Other',
    'Preschool Teachers, Except Special Education',
    'Psychology Teachers, Postsecondary',
    'Recreation and Fitness Studies Teachers, Postsecondary',
    'Secondary School Teachers, Except Special and Career/Technical Education',
    'Self-Enrichment Teachers',
    'Social Sciences Teachers, Postsecondary, All Other',
    'Sociology Teachers, Postsecondary',
    'Special Education Teachers, All Other',
    'Special Education Teachers, Elementary School',
    'Special Education Teachers, Kindergarten',
    'Special Education Teachers, Middle School',
    'Special Education Teachers, Preschool',
    'Special Education Teachers, Secondary School',
    'Substitute Teachers, Short-Term',
    'Teachers and Instructors, All Other',
    'Teaching Assistants, All Other',
    'Teaching Assistants, Postsecondary',
    'Teaching Assistants, Preschool, Elementary, Middle, and Secondary School, Except Special Education',
    'Teaching Assistants, Special Education',
  ],
  'BSIT': [
    'Blockchain Engineers',
    'Business Intelligence Analysts',
    'Cardiovascular Technologists and Technicians',
    'Cartographers and Photogrammetrists',
    'Clinical Data Managers',
    'Clinical Research Coordinators',
    'Computer and Information Research Scientists',
    'Computer and Information Systems Managers',
    'Computer Hardware Engineers',
    'Computer Network Architects',
    'Computer Network Support Specialists',
    'Computer Numerically Controlled Tool Programmers',
    'Computer Occupations, All Other',
    'Computer Programmers',
    'Computer Science Teachers, Postsecondary',
    'Computer Systems Analysts',
    'Computer Systems Engineers/Architects',
    'Computer User Support Specialists',
    'Computer, Automated Teller, and Office Machine Repairers',
    'Credit Analysts',
    'Customer Service Representatives',
    'Data Scientists',
    'Data Warehousing Specialists',
    'Database Administrators',
    'Database Architects',
    'Digital Forensics Analysts',
    'Document Management Specialists',
    'Economists',
    'Electro-Mechanical and Mechatronics Technologists and Technicians',
    'Energy Auditors',
    'Energy Engineers, Except Wind and Solar',
    'Financial and Investment Analysts',
    'Geographic Information Systems Technologists and Technicians',
    'Health Informatics Specialists',
    'Health Information Technologists and Medical Registrars',
    'Information Security Analysts',
    'Information Security Engineers',
    'Intelligence Analysts',
    'Loss Prevention Managers',
    'Management Analysts',
    'Manufacturing Engineers',
    'Market Research Analysts and Marketing Specialists',
    'Mechatronics Engineers',
    'Microsystems Engineers',
    'Mining and Geological Engineers, Including Mining Safety Engineers',
    'Nanosystems Engineers',
    'Nanotechnology Engineering Technologists and Technicians',
    'Network and Computer Systems Administrators',
    'Occupational Health and Safety Technicians',
    'Operations Research Analysts',
    'Penetration Testers',
    'Quality Control Systems Managers',
    'Remote Sensing Scientists and Technologists',
    'Retail Loss Prevention Specialists',
    'Robotics Technicians',
    'Search Marketing Strategists',
    'Security Management Specialists',
    'Software Developers',
    'Software Quality Assurance Analysts and Testers',
    'Solar Energy Installation Managers',
    'Solar Energy Systems Engineers',
    'Solar Sales Representatives and Assessors',
    'Special Effects Artists and Animators',
    'Statistical Assistants',
    'Telecommunications Engineering Specialists',
    'Web Administrators',
    'Web and Digital Interface Designers',
    'Web Developers',
  ],
  'BSN': [
    'Acute Care Nurses',
    'Advanced Practice Psychiatric Nurses',
    'Career/Technical Education Teachers, Middle School',
    'Career/Technical Education Teachers, Postsecondary',
    'Career/Technical Education Teachers, Secondary School',
    'Childcare Workers',
    'Clinical and Counseling Psychologists',
    'Clinical Data Managers',
    'Clinical Neuropsychologists',
    'Clinical Nurse Specialists',
    'Clinical Research Coordinators',
    'Community Health Workers',
    'Critical Care Nurses',
    'Dental Hygienists',
    'Diagnostic Medical Sonographers',
    'Education and Childcare Administrators, Preschool and Daycare',
    'Educational, Guidance, and Career Counselors and Advisors',
    'Emergency Medical Technicians',
    'Environmental Science and Protection Technicians, Including Health',
    'Environmental Scientists and Specialists, Including Health',
    'Genetic Counselors',
    'Health and Safety Engineers, Except Mining Safety Engineers and Inspectors',
    'Health Education Specialists',
    'Health Informatics Specialists',
    'Health Information Technologists and Medical Registrars',
    'Health Technologists and Technicians, All Other',
    'Healthcare Diagnosing or Treating Practitioners, All Other',
    'Healthcare Practitioners and Technical Workers, All Other',
    'Healthcare Social Workers',
    'Healthcare Support Workers, All Other',
    'Home Health Aides',
    'Licensed Practical and Licensed Vocational Nurses',
    'Medical and Clinical Laboratory Technicians',
    'Medical and Clinical Laboratory Technologists',
    'Medical and Health Services Managers',
    'Medical Appliance Technicians',
    'Medical Assistants',
    'Medical Dosimetrists',
    'Medical Equipment Preparers',
    'Medical Equipment Repairers',
    'Medical Records Specialists',
    'Medical Scientists, Except Epidemiologists',
    'Medical Secretaries and Administrative Assistants',
    'Medical Transcriptionists',
    'Mental Health and Substance Abuse Social Workers',
    'Mental Health Counselors',
    'Middle School Teachers, Except Special and Career/Technical Education',
    'Nurse Midwives',
    'Nurse Practitioners',
    'Nursing Assistants',
    'Nursing Instructors and Teachers, Postsecondary',
    'Occupational Health and Safety Specialists',
    'Occupational Health and Safety Technicians',
    'Ophthalmic Medical Technicians',
    'Ophthalmic Medical Technologists',
    'Paramedics',
    'Patient Representatives',
    'Personal Care Aides',
    'Personal Care and Service Workers, All Other',
    'Physician Assistants',
    'Psychiatric Aides',
    'Psychiatric Technicians',
    'Radiation Therapists',
    'Recreational Therapists',
    'Registered Nurses',
    'Respiratory Therapists',
    'Secondary School Teachers, Except Special and Career/Technical Education',
    'Secretaries and Administrative Assistants, Except Legal, Medical, and Executive',
  ],
};

module.exports = { PROGRAM_TITLE_MAPPING };
