const PROGRAM_TITLE_MAPPING = {
  'BSA': [
    'Accountants and Auditors',
    'Bookkeeping, Accounting, and Auditing Clerks',
    'Budget Analysts',
    'Bill and Account Collectors',
    'Business Teachers, Postsecondary',
    'Compliance Managers',
    'Compliance Officers',
    'Cost Estimators',
    'Energy Auditors',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'First-Line Supervisors of Retail Sales Workers',
    'New Accounts Clerks',
    'Tax Examiners and Collectors, and Revenue Agents',
    'Tax Preparers',
    'Treasurers and Controllers',
  ],
  'BSBA_ENTREP': [
    'Business Teachers, Postsecondary',
    'Business Operations Specialists, All Other',
    'Project Management Specialists',
    'Farm and Home Management Educators',
    'First-Line Supervisors of Retail Sales Workers',
    'General and Operations Managers',
    'Information Technology Project Managers',
    'Management Analysts',
    'Market Research Analysts and Marketing Specialists',
    'Marketing Managers',
    'Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel',
    'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
    'Securities, Commodities, and Financial Services Sales Agents',
    'Advertising Sales Agents',
    'Agents and Business Managers of Artists, Performers, and Athletes',
    'Appraisers of Personal and Business Property',
    'Business Continuity Planners',
    'Business Intelligence Analysts',
    'Computer Systems Analysts',
    'Construction Managers',
    'Cost Estimators',
    'Document Management Specialists',
    'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
    'Driver/Sales Workers',
    'Emergency Management Directors',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'Parts Salespersons',
    'Real Estate Sales Agents',
    'Retail Salespersons',
    'Sales and Related Workers, All Other',
    'Sales Managers',
    'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
    'Search Marketing Strategists',
    'Security Management Specialists',
    'Solar Sales Representatives and Assessors',
    'Training and Development Managers',
    'Training and Development Specialists',
    'Wind Energy Operations Managers',
  ],
  'BSBA_MARKETING': [
    'Market Research Analysts and Marketing Specialists',
    'Advertising Sales Agents',
    'Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel',
    'Advertising and Promotions Managers',
    'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
    'Driver/Sales Workers',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'First-Line Supervisors of Retail Sales Workers',
    'Marketing Managers',
    'Parts Salespersons',
    'Public Relations Managers',
    'Public Relations Specialists',
    'Real Estate Sales Agents',
    'Retail Salespersons',
    'Sales and Related Workers, All Other',
    'Sales Engineers',
    'Sales Managers',
    'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
    'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
    'Search Marketing Strategists',
    'Securities, Commodities, and Financial Services Sales Agents',
    'Solar Sales Representatives and Assessors',
  ],
  'BSCS': [
    'Computer Programmers',
    'Software Developers',
    'Web Developers',
    'Software Quality Assurance Analysts and Testers',
    'Database Administrators',
    'Bioinformatics Scientists',
    'Computer Network Architects',
    'Computer Numerically Controlled Tool Programmers',
    'Computer Systems Analysts',
    'Data Scientists',
    'Database Architects',
    'Network and Computer Systems Administrators',
    'Web and Digital Interface Designers',
    'Bioinformatics Technicians',
    'Clinical Data Managers',
    'Computer and Information Research Scientists',
    'Computer and Information Systems Managers',
    'Computer Network Support Specialists',
    'Computer User Support Specialists',
    'Data Warehousing Specialists',
    'Health Information Technologists and Medical Registrars',
    'Information Security Analysts',
    'Information Security Engineers',
    'Aerospace Engineering and Operations Technologists and Technicians',
    'Cartographers and Photogrammetrists',
    'Computer Hardware Engineers',
    'Computer Occupations, All Other',
    'Computer Science Teachers, Postsecondary',
    'Computer Systems Engineers/Architects',
    'Computer, Automated Teller, and Office Machine Repairers',
    'Geographic Information Systems Technologists and Technicians',
    'Intelligence Analysts',
    'Operations Research Analysts',
    'Web Administrators',
  ],
  'BSECE': [
    'Electrical and Electronics Drafters',
    'Electrical and Electronics Repairers, Commercial and Industrial Equipment',
    'Electronics Engineers, Except Computer',
    'Electrical and Electronic Engineering Technologists and Technicians',
    'Electrical and Electronics Installers and Repairers, Transportation Equipment',
    'Electrical and Electronics Repairers, Powerhouse, Substation, and Relay',
    'Computer Network Architects',
    'Computer Network Support Specialists',
    'Information Security Engineers',
    'Network and Computer Systems Administrators',
    'Semiconductor Processing Technicians',
    'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
    'Calibration Technologists and Technicians',
    'Computer Systems Analysts',
    'Computer Systems Engineers/Architects',
    'Database Architects',
    'Electrical and Electronic Equipment Assemblers',
    'Electrical Engineers',
    'Electrical Power-Line Installers and Repairers',
    'Excavating and Loading Machine and Dragline Operators, Surface Mining',
    'Helpers--Installation, Maintenance, and Repair Workers',
    'Information Security Analysts',
    'Maintenance and Repair Workers, General',
    'Public Safety Telecommunicators',
    'Software Developers',
    'Solar Photovoltaic Installers',
    'Telecommunications Engineering Specialists',
    'Telecommunications Equipment Installers and Repairers, Except Line Installers',
    'Telecommunications Line Installers and Repairers',
    'Timing Device Assemblers and Adjusters',
    'Wind Turbine Service Technicians',
  ],
  'BSED': [
    'Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors',
    'Education Teachers, Postsecondary',
    'Special Education Teachers, Secondary School',
    'Teaching Assistants, Preschool, Elementary, Middle, and Secondary School, Except Special Education',
    'Teaching Assistants, Special Education',
    'Career/Technical Education Teachers, Secondary School',
    'Secondary School Teachers, Except Special and Career/Technical Education',
    'Career/Technical Education Teachers, Postsecondary',
    'English Language and Literature Teachers, Postsecondary',
    'Foreign Language and Literature Teachers, Postsecondary',
    'Special Education Teachers, Elementary School',
    'Special Education Teachers, Kindergarten',
    'Special Education Teachers, Middle School',
    'Special Education Teachers, Preschool',
    'Career/Technical Education Teachers, Middle School',
    'Elementary School Teachers, Except Special Education',
    'Kindergarten Teachers, Except Special Education',
    'Middle School Teachers, Except Special and Career/Technical Education',
    'Preschool Teachers, Except Special Education',
    'Special Education Teachers, All Other',
    'Teachers and Instructors, All Other',
    'Anthropology and Archeology Teachers, Postsecondary',
    'Area, Ethnic, and Cultural Studies Teachers, Postsecondary',
    'Art, Drama, and Music Teachers, Postsecondary',
    'Business Teachers, Postsecondary',
    'Communications Teachers, Postsecondary',
    'Computer Science Teachers, Postsecondary',
    'Criminal Justice and Law Enforcement Teachers, Postsecondary',
    'Economics Teachers, Postsecondary',
    'Education Administrators, Kindergarten through Secondary',
    'Family and Consumer Sciences Teachers, Postsecondary',
    'Geography Teachers, Postsecondary',
    'History Teachers, Postsecondary',
    'Instructional Coordinators',
    'Mathematical Science Teachers, Postsecondary',
    'Philosophy and Religion Teachers, Postsecondary',
    'Political Science Teachers, Postsecondary',
    'Psychology Teachers, Postsecondary',
    'Recreation and Fitness Studies Teachers, Postsecondary',
    'Self-Enrichment Teachers',
    'Sociology Teachers, Postsecondary',
    'Adapted Physical Education Specialists',
    'Education Administrators, All Other',
    'Education Administrators, Postsecondary',
    'Education and Childcare Administrators, Preschool and Daycare',
    'Educational Instruction and Library Workers, All Other',
    'Educational, Guidance, and Career Counselors and Advisors',
    'Exercise Trainers and Group Fitness Instructors',
    'Health Education Specialists',
    'Postsecondary Teachers, All Other',
    'Social Sciences Teachers, Postsecondary, All Other',
    'Substitute Teachers, Short-Term',
    'Teaching Assistants, All Other',
    'Teaching Assistants, Postsecondary',
  ],
  'BSN': [
    'Clinical Nurse Specialists',
    'Registered Nurses',
    'Acute Care Nurses',
    'Critical Care Nurses',
    'Health Information Technologists and Medical Registrars',
    'Healthcare Social Workers',
    'Home Health Aides',
    'Licensed Practical and Licensed Vocational Nurses',
    'Medical and Health Services Managers',
    'Medical Records Specialists',
    'Nurse Midwives',
    'Nursing Assistants',
    'Nursing Instructors and Teachers, Postsecondary',
    'Ophthalmic Medical Technicians',
    'Ophthalmic Medical Technologists',
    'Clinical and Counseling Psychologists',
    'Clinical Data Managers',
    'Health Informatics Specialists',
    'Healthcare Diagnosing or Treating Practitioners, All Other',
    'Healthcare Practitioners and Technical Workers, All Other',
    'Healthcare Support Workers, All Other',
    'Medical and Clinical Laboratory Technicians',
    'Medical and Clinical Laboratory Technologists',
    'Medical Assistants',
    'Medical Equipment Preparers',
    'Medical Scientists, Except Epidemiologists',
    'Medical Transcriptionists',
    'Nurse Practitioners',
    'Patient Representatives',
    'Psychiatric Technicians',
    'Advanced Practice Psychiatric Nurses',
    'Clinical Neuropsychologists',
    'Community Health Workers',
    'Dental Hygienists',
    'Emergency Medical Technicians',
    'Health Education Specialists',
    'Medical Secretaries and Administrative Assistants',
    'Physician Assistants',
    'Psychiatric Aides',
    'Recreational Therapists',
    'Career/Technical Education Teachers, Middle School',
    'Career/Technical Education Teachers, Postsecondary',
    'Career/Technical Education Teachers, Secondary School',
    'Childcare Workers',
    'Clinical Research Coordinators',
    'Diagnostic Medical Sonographers',
    'Education and Childcare Administrators, Preschool and Daycare',
    'Educational, Guidance, and Career Counselors and Advisors',
    'Environmental Science and Protection Technicians, Including Health',
    'Environmental Scientists and Specialists, Including Health',
    'Genetic Counselors',
    'Health and Safety Engineers, Except Mining Safety Engineers and Inspectors',
    'Health Technologists and Technicians, All Other',
    'Medical Appliance Technicians',
    'Medical Dosimetrists',
    'Medical Equipment Repairers',
    'Mental Health and Substance Abuse Social Workers',
    'Mental Health Counselors',
    'Middle School Teachers, Except Special and Career/Technical Education',
    'Occupational Health and Safety Specialists',
    'Occupational Health and Safety Technicians',
    'Paramedics',
    'Personal Care Aides',
    'Personal Care and Service Workers, All Other',
    'Radiation Therapists',
    'Respiratory Therapists',
    'Secondary School Teachers, Except Special and Career/Technical Education',
    'Secretaries and Administrative Assistants, Except Legal, Medical, and Executive',
  ],
  'BSIT': [
    'Network and Computer Systems Administrators',
    'Computer Systems Analysts',
    'Software Developers',
    'Computer Programmers',
    'Database Administrators',
    'Web Developers',
    'Computer Network Architects',
    'Computer Network Support Specialists',
    'Database Architects',
    'Information Security Engineers',
    'Software Quality Assurance Analysts and Testers',
    'Computer and Information Systems Managers',
    'Computer Numerically Controlled Tool Programmers',
    'Computer Systems Engineers/Architects',
    'Information Security Analysts',
    'Computer User Support Specialists',
    'Geographic Information Systems Technologists and Technicians',
    'Health Information Technologists and Medical Registrars',
    'Intelligence Analysts',
    'Web and Digital Interface Designers',
    'Clinical Data Managers',
    'Computer and Information Research Scientists',
    'Computer, Automated Teller, and Office Machine Repairers',
    'Data Scientists',
    'Data Warehousing Specialists',
    'Operations Research Analysts',
    'Blockchain Engineers',
    'Cartographers and Photogrammetrists',
    'Computer Hardware Engineers',
    'Computer Occupations, All Other',
    'Computer Science Teachers, Postsecondary',
    'Digital Forensics Analysts',
    'Health Informatics Specialists',
    'Mechatronics Engineers',
    'Microsystems Engineers',
    'Nanosystems Engineers',
    'Penetration Testers',
    'Quality Control Systems Managers',
    'Remote Sensing Scientists and Technologists',
    'Solar Energy Systems Engineers',
    'Telecommunications Engineering Specialists',
    'Web Administrators',
    'Business Intelligence Analysts',
    'Cardiovascular Technologists and Technicians',
    'Clinical Research Coordinators',
    'Credit Analysts',
    'Customer Service Representatives',
    'Document Management Specialists',
    'Economists',
    'Electro-Mechanical and Mechatronics Technologists and Technicians',
    'Energy Auditors',
    'Energy Engineers, Except Wind and Solar',
    'Financial and Investment Analysts',
    'Loss Prevention Managers',
    'Management Analysts',
    'Manufacturing Engineers',
    'Market Research Analysts and Marketing Specialists',
    'Mining and Geological Engineers, Including Mining Safety Engineers',
    'Nanotechnology Engineering Technologists and Technicians',
    'Occupational Health and Safety Technicians',
    'Retail Loss Prevention Specialists',
    'Robotics Technicians',
    'Search Marketing Strategists',
    'Security Management Specialists',
    'Solar Energy Installation Managers',
    'Solar Sales Representatives and Assessors',
    'Special Effects Artists and Animators',
    'Statistical Assistants',
  ],
};

module.exports = { PROGRAM_TITLE_MAPPING };

